// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/flinkcoin/mono/apps/broker/internal/networking"
)

// Injectors from wire.go:

func Init() *Broker {
	netNet := networking.NewNode()
	broker := NewBroker(netNet)
	return broker
}
