// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: libs/schema/pkg/broker/comm.proto

package broker

import (
	core "github.com/flinkcoin/mono/libs/schema/pkg/core"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Magic         int32                  `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	NetowrkId     int32                  `protobuf:"varint,2,opt,name=netowrkId,proto3" json:"netowrkId,omitempty"`
	VersionMax    int32                  `protobuf:"varint,3,opt,name=versionMax,proto3" json:"versionMax,omitempty"`
	VersionUsing  int32                  `protobuf:"varint,4,opt,name=versionUsing,proto3" json:"versionUsing,omitempty"`
	VersionMin    int32                  `protobuf:"varint,5,opt,name=versionMin,proto3" json:"versionMin,omitempty"`
	Any           *anypb.Any             `protobuf:"bytes,6,opt,name=any,proto3" json:"any,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetMagic() int32 {
	if x != nil {
		return x.Magic
	}
	return 0
}

func (x *Message) GetNetowrkId() int32 {
	if x != nil {
		return x.NetowrkId
	}
	return 0
}

func (x *Message) GetVersionMax() int32 {
	if x != nil {
		return x.VersionMax
	}
	return 0
}

func (x *Message) GetVersionUsing() int32 {
	if x != nil {
		return x.VersionUsing
	}
	return 0
}

func (x *Message) GetVersionMin() int32 {
	if x != nil {
		return x.VersionMin
	}
	return 0
}

func (x *Message) GetAny() *anypb.Any {
	if x != nil {
		return x.Any
	}
	return nil
}

type Message_IAmAlive struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Peers         []*Message_IAmAlive_Peer `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_IAmAlive) Reset() {
	*x = Message_IAmAlive{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_IAmAlive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_IAmAlive) ProtoMessage() {}

func (x *Message_IAmAlive) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_IAmAlive.ProtoReflect.Descriptor instead.
func (*Message_IAmAlive) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Message_IAmAlive) GetPeers() []*Message_IAmAlive_Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type Message_AuthenticationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         []byte                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_AuthenticationReq) Reset() {
	*x = Message_AuthenticationReq{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_AuthenticationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_AuthenticationReq) ProtoMessage() {}

func (x *Message_AuthenticationReq) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_AuthenticationReq.ProtoReflect.Descriptor instead.
func (*Message_AuthenticationReq) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Message_AuthenticationReq) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type Message_AuthenticationRes struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Body          *Message_AuthenticationRes_Body `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Signature     []byte                          `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_AuthenticationRes) Reset() {
	*x = Message_AuthenticationRes{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_AuthenticationRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_AuthenticationRes) ProtoMessage() {}

func (x *Message_AuthenticationRes) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_AuthenticationRes.ProtoReflect.Descriptor instead.
func (*Message_AuthenticationRes) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Message_AuthenticationRes) GetBody() *Message_AuthenticationRes_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Message_AuthenticationRes) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Message_NodePub struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          *Message_NodePub_Body  `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_NodePub) Reset() {
	*x = Message_NodePub{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_NodePub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_NodePub) ProtoMessage() {}

func (x *Message_NodePub) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_NodePub.ProtoReflect.Descriptor instead.
func (*Message_NodePub) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Message_NodePub) GetBody() *Message_NodePub_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Message_NodePub) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Message_BlockPub struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          *Message_BlockPub_Body `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_BlockPub) Reset() {
	*x = Message_BlockPub{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_BlockPub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_BlockPub) ProtoMessage() {}

func (x *Message_BlockPub) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_BlockPub.ProtoReflect.Descriptor instead.
func (*Message_BlockPub) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Message_BlockPub) GetBody() *Message_BlockPub_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Message_BlockPub) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Message_PaymentReq struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Body          *Message_PaymentReq_Body `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Signature     []byte                   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_PaymentReq) Reset() {
	*x = Message_PaymentReq{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_PaymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_PaymentReq) ProtoMessage() {}

func (x *Message_PaymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_PaymentReq.ProtoReflect.Descriptor instead.
func (*Message_PaymentReq) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 5}
}

func (x *Message_PaymentReq) GetBody() *Message_PaymentReq_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Message_PaymentReq) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Message_BlockConfirmPub struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Body          *Message_BlockConfirmPub_Body `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Signature     []byte                        `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_BlockConfirmPub) Reset() {
	*x = Message_BlockConfirmPub{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_BlockConfirmPub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_BlockConfirmPub) ProtoMessage() {}

func (x *Message_BlockConfirmPub) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_BlockConfirmPub.ProtoReflect.Descriptor instead.
func (*Message_BlockConfirmPub) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 6}
}

func (x *Message_BlockConfirmPub) GetBody() *Message_BlockConfirmPub_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Message_BlockConfirmPub) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Message_BlockVerifyPub struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Body          *Message_BlockVerifyPub_Body `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Signature     []byte                       `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_BlockVerifyPub) Reset() {
	*x = Message_BlockVerifyPub{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_BlockVerifyPub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_BlockVerifyPub) ProtoMessage() {}

func (x *Message_BlockVerifyPub) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_BlockVerifyPub.ProtoReflect.Descriptor instead.
func (*Message_BlockVerifyPub) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 7}
}

func (x *Message_BlockVerifyPub) GetBody() *Message_BlockVerifyPub_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Message_BlockVerifyPub) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Message_BlockVerifyConfirmPub struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Body          *Message_BlockVerifyConfirmPub_Body `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Signature     []byte                              `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_BlockVerifyConfirmPub) Reset() {
	*x = Message_BlockVerifyConfirmPub{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_BlockVerifyConfirmPub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_BlockVerifyConfirmPub) ProtoMessage() {}

func (x *Message_BlockVerifyConfirmPub) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_BlockVerifyConfirmPub.ProtoReflect.Descriptor instead.
func (*Message_BlockVerifyConfirmPub) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 8}
}

func (x *Message_BlockVerifyConfirmPub) GetBody() *Message_BlockVerifyConfirmPub_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Message_BlockVerifyConfirmPub) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Message_BlockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     []byte                 `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	FromBlockHash []byte                 `protobuf:"bytes,2,opt,name=fromBlockHash,proto3" json:"fromBlockHash,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_BlockReq) Reset() {
	*x = Message_BlockReq{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_BlockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_BlockReq) ProtoMessage() {}

func (x *Message_BlockReq) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_BlockReq.ProtoReflect.Descriptor instead.
func (*Message_BlockReq) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 9}
}

func (x *Message_BlockReq) GetAccountId() []byte {
	if x != nil {
		return x.AccountId
	}
	return nil
}

func (x *Message_BlockReq) GetFromBlockHash() []byte {
	if x != nil {
		return x.FromBlockHash
	}
	return nil
}

func (x *Message_BlockReq) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type Message_BlockRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     []byte                 `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	FromBlockHash []byte                 `protobuf:"bytes,2,opt,name=fromBlockHash,proto3" json:"fromBlockHash,omitempty"`
	Blocks        []*core.FullBlock      `protobuf:"bytes,3,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_BlockRes) Reset() {
	*x = Message_BlockRes{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_BlockRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_BlockRes) ProtoMessage() {}

func (x *Message_BlockRes) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_BlockRes.ProtoReflect.Descriptor instead.
func (*Message_BlockRes) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 10}
}

func (x *Message_BlockRes) GetAccountId() []byte {
	if x != nil {
		return x.AccountId
	}
	return nil
}

func (x *Message_BlockRes) GetFromBlockHash() []byte {
	if x != nil {
		return x.FromBlockHash
	}
	return nil
}

func (x *Message_BlockRes) GetBlocks() []*core.FullBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type Message_FrontierReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         []byte                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	Age           int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_FrontierReq) Reset() {
	*x = Message_FrontierReq{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_FrontierReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_FrontierReq) ProtoMessage() {}

func (x *Message_FrontierReq) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_FrontierReq.ProtoReflect.Descriptor instead.
func (*Message_FrontierReq) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 11}
}

func (x *Message_FrontierReq) GetStart() []byte {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Message_FrontierReq) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Message_FrontierReq) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Message_FrontierRes struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Entries       []*Message_FrontierRes_Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_FrontierRes) Reset() {
	*x = Message_FrontierRes{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_FrontierRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_FrontierRes) ProtoMessage() {}

func (x *Message_FrontierRes) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_FrontierRes.ProtoReflect.Descriptor instead.
func (*Message_FrontierRes) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 12}
}

func (x *Message_FrontierRes) GetEntries() []*Message_FrontierRes_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type Message_TelemetryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *core.Block            `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_TelemetryReq) Reset() {
	*x = Message_TelemetryReq{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_TelemetryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_TelemetryReq) ProtoMessage() {}

func (x *Message_TelemetryReq) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_TelemetryReq.ProtoReflect.Descriptor instead.
func (*Message_TelemetryReq) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 13}
}

func (x *Message_TelemetryReq) GetBlock() *core.Block {
	if x != nil {
		return x.Block
	}
	return nil
}

type Message_TelemetryRes struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Signature           []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	NodeId              []byte                 `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	BlockCount          int64                  `protobuf:"varint,3,opt,name=blockCount,proto3" json:"blockCount,omitempty"`
	CementedBlockCount  int64                  `protobuf:"varint,4,opt,name=cementedBlockCount,proto3" json:"cementedBlockCount,omitempty"`
	UncheckedBlockCount int64                  `protobuf:"varint,5,opt,name=uncheckedBlockCount,proto3" json:"uncheckedBlockCount,omitempty"`
	AccountCount        int64                  `protobuf:"varint,6,opt,name=accountCount,proto3" json:"accountCount,omitempty"`
	BandwidthCap        int64                  `protobuf:"varint,7,opt,name=bandwidthCap,proto3" json:"bandwidthCap,omitempty"`
	Uptime              int64                  `protobuf:"varint,8,opt,name=uptime,proto3" json:"uptime,omitempty"`
	PeerCount           int32                  `protobuf:"varint,9,opt,name=peerCount,proto3" json:"peerCount,omitempty"`
	ProtocolVersion     int32                  `protobuf:"varint,10,opt,name=protocolVersion,proto3" json:"protocolVersion,omitempty"`
	GenesisBlock        []byte                 `protobuf:"bytes,11,opt,name=genesisBlock,proto3" json:"genesisBlock,omitempty"`
	MajorVersion        int32                  `protobuf:"varint,12,opt,name=majorVersion,proto3" json:"majorVersion,omitempty"`
	MinorVersion        int32                  `protobuf:"varint,13,opt,name=minorVersion,proto3" json:"minorVersion,omitempty"`
	Maker               int32                  `protobuf:"varint,14,opt,name=maker,proto3" json:"maker,omitempty"`
	Timestamp           int64                  `protobuf:"varint,15,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ActiveDifficulty    int64                  `protobuf:"varint,16,opt,name=activeDifficulty,proto3" json:"activeDifficulty,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Message_TelemetryRes) Reset() {
	*x = Message_TelemetryRes{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_TelemetryRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_TelemetryRes) ProtoMessage() {}

func (x *Message_TelemetryRes) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_TelemetryRes.ProtoReflect.Descriptor instead.
func (*Message_TelemetryRes) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 14}
}

func (x *Message_TelemetryRes) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Message_TelemetryRes) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *Message_TelemetryRes) GetBlockCount() int64 {
	if x != nil {
		return x.BlockCount
	}
	return 0
}

func (x *Message_TelemetryRes) GetCementedBlockCount() int64 {
	if x != nil {
		return x.CementedBlockCount
	}
	return 0
}

func (x *Message_TelemetryRes) GetUncheckedBlockCount() int64 {
	if x != nil {
		return x.UncheckedBlockCount
	}
	return 0
}

func (x *Message_TelemetryRes) GetAccountCount() int64 {
	if x != nil {
		return x.AccountCount
	}
	return 0
}

func (x *Message_TelemetryRes) GetBandwidthCap() int64 {
	if x != nil {
		return x.BandwidthCap
	}
	return 0
}

func (x *Message_TelemetryRes) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *Message_TelemetryRes) GetPeerCount() int32 {
	if x != nil {
		return x.PeerCount
	}
	return 0
}

func (x *Message_TelemetryRes) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Message_TelemetryRes) GetGenesisBlock() []byte {
	if x != nil {
		return x.GenesisBlock
	}
	return nil
}

func (x *Message_TelemetryRes) GetMajorVersion() int32 {
	if x != nil {
		return x.MajorVersion
	}
	return 0
}

func (x *Message_TelemetryRes) GetMinorVersion() int32 {
	if x != nil {
		return x.MinorVersion
	}
	return 0
}

func (x *Message_TelemetryRes) GetMaker() int32 {
	if x != nil {
		return x.Maker
	}
	return 0
}

func (x *Message_TelemetryRes) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Message_TelemetryRes) GetActiveDifficulty() int64 {
	if x != nil {
		return x.ActiveDifficulty
	}
	return 0
}

type Message_Publish struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *core.Block            `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_Publish) Reset() {
	*x = Message_Publish{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_Publish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Publish) ProtoMessage() {}

func (x *Message_Publish) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Publish.ProtoReflect.Descriptor instead.
func (*Message_Publish) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 15}
}

func (x *Message_Publish) GetBlock() *core.Block {
	if x != nil {
		return x.Block
	}
	return nil
}

type Message_AccountBulkPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         []byte                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	Stop          []byte                 `protobuf:"bytes,2,opt,name=stop,proto3" json:"stop,omitempty"`
	Blocks        []*core.Block          `protobuf:"bytes,3,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_AccountBulkPush) Reset() {
	*x = Message_AccountBulkPush{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_AccountBulkPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_AccountBulkPush) ProtoMessage() {}

func (x *Message_AccountBulkPush) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_AccountBulkPush.ProtoReflect.Descriptor instead.
func (*Message_AccountBulkPush) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 16}
}

func (x *Message_AccountBulkPush) GetStart() []byte {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Message_AccountBulkPush) GetStop() []byte {
	if x != nil {
		return x.Stop
	}
	return nil
}

func (x *Message_AccountBulkPush) GetBlocks() []*core.Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type Message_AccountBulkPull struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         []byte                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	Stop          []byte                 `protobuf:"bytes,2,opt,name=stop,proto3" json:"stop,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_AccountBulkPull) Reset() {
	*x = Message_AccountBulkPull{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_AccountBulkPull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_AccountBulkPull) ProtoMessage() {}

func (x *Message_AccountBulkPull) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_AccountBulkPull.ProtoReflect.Descriptor instead.
func (*Message_AccountBulkPull) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 17}
}

func (x *Message_AccountBulkPull) GetStart() []byte {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Message_AccountBulkPull) GetStop() []byte {
	if x != nil {
		return x.Stop
	}
	return nil
}

func (x *Message_AccountBulkPull) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Message_BulkPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         []byte                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	Stop          []byte                 `protobuf:"bytes,2,opt,name=stop,proto3" json:"stop,omitempty"`
	Blocks        []*core.Block          `protobuf:"bytes,3,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_BulkPush) Reset() {
	*x = Message_BulkPush{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_BulkPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_BulkPush) ProtoMessage() {}

func (x *Message_BulkPush) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_BulkPush.ProtoReflect.Descriptor instead.
func (*Message_BulkPush) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 18}
}

func (x *Message_BulkPush) GetStart() []byte {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Message_BulkPush) GetStop() []byte {
	if x != nil {
		return x.Stop
	}
	return nil
}

func (x *Message_BulkPush) GetBlocks() []*core.Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type Message_BulkPull struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         []byte                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	Stop          []byte                 `protobuf:"bytes,2,opt,name=stop,proto3" json:"stop,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_BulkPull) Reset() {
	*x = Message_BulkPull{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_BulkPull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_BulkPull) ProtoMessage() {}

func (x *Message_BulkPull) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_BulkPull.ProtoReflect.Descriptor instead.
func (*Message_BulkPull) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 19}
}

func (x *Message_BulkPull) GetStart() []byte {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Message_BulkPull) GetStop() []byte {
	if x != nil {
		return x.Stop
	}
	return nil
}

func (x *Message_BulkPull) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Message_ConfirmReqByHash struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	HashPairs     []*Message_ConfirmReqByHash_HashPair `protobuf:"bytes,1,rep,name=hashPairs,proto3" json:"hashPairs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_ConfirmReqByHash) Reset() {
	*x = Message_ConfirmReqByHash{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_ConfirmReqByHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_ConfirmReqByHash) ProtoMessage() {}

func (x *Message_ConfirmReqByHash) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_ConfirmReqByHash.ProtoReflect.Descriptor instead.
func (*Message_ConfirmReqByHash) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 20}
}

func (x *Message_ConfirmReqByHash) GetHashPairs() []*Message_ConfirmReqByHash_HashPair {
	if x != nil {
		return x.HashPairs
	}
	return nil
}

type Message_ConfirmReq struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	ConfirmReqByHash *Message_ConfirmReqByHash `protobuf:"bytes,1,opt,name=confirmReqByHash,proto3" json:"confirmReqByHash,omitempty"`
	Block            *core.Block               `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Message_ConfirmReq) Reset() {
	*x = Message_ConfirmReq{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_ConfirmReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_ConfirmReq) ProtoMessage() {}

func (x *Message_ConfirmReq) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_ConfirmReq.ProtoReflect.Descriptor instead.
func (*Message_ConfirmReq) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 21}
}

func (x *Message_ConfirmReq) GetConfirmReqByHash() *Message_ConfirmReqByHash {
	if x != nil {
		return x.ConfirmReqByHash
	}
	return nil
}

func (x *Message_ConfirmReq) GetBlock() *core.Block {
	if x != nil {
		return x.Block
	}
	return nil
}

type Message_VoteByHash struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hashes        [][]byte               `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_VoteByHash) Reset() {
	*x = Message_VoteByHash{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_VoteByHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_VoteByHash) ProtoMessage() {}

func (x *Message_VoteByHash) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_VoteByHash.ProtoReflect.Descriptor instead.
func (*Message_VoteByHash) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 22}
}

func (x *Message_VoteByHash) GetHashes() [][]byte {
	if x != nil {
		return x.Hashes
	}
	return nil
}

type Message_ConfirmRes struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	VoteCommon    *Message_ConfirmRes_VoteCommon `protobuf:"bytes,1,opt,name=voteCommon,proto3" json:"voteCommon,omitempty"`
	VoteByHash    *Message_VoteByHash            `protobuf:"bytes,2,opt,name=voteByHash,proto3" json:"voteByHash,omitempty"`
	Block         *core.Block                    `protobuf:"bytes,3,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_ConfirmRes) Reset() {
	*x = Message_ConfirmRes{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_ConfirmRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_ConfirmRes) ProtoMessage() {}

func (x *Message_ConfirmRes) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_ConfirmRes.ProtoReflect.Descriptor instead.
func (*Message_ConfirmRes) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 23}
}

func (x *Message_ConfirmRes) GetVoteCommon() *Message_ConfirmRes_VoteCommon {
	if x != nil {
		return x.VoteCommon
	}
	return nil
}

func (x *Message_ConfirmRes) GetVoteByHash() *Message_VoteByHash {
	if x != nil {
		return x.VoteByHash
	}
	return nil
}

func (x *Message_ConfirmRes) GetBlock() *core.Block {
	if x != nil {
		return x.Block
	}
	return nil
}

type Message_IAmAlive_Peer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_IAmAlive_Peer) Reset() {
	*x = Message_IAmAlive_Peer{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_IAmAlive_Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_IAmAlive_Peer) ProtoMessage() {}

func (x *Message_IAmAlive_Peer) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_IAmAlive_Peer.ProtoReflect.Descriptor instead.
func (*Message_IAmAlive_Peer) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Message_IAmAlive_Peer) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Message_IAmAlive_Peer) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type Message_AuthenticationRes_Body struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         []byte                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Node          *core.Node             `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	NodeAddress   *core.NodeAddress      `protobuf:"bytes,3,opt,name=nodeAddress,proto3" json:"nodeAddress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_AuthenticationRes_Body) Reset() {
	*x = Message_AuthenticationRes_Body{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_AuthenticationRes_Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_AuthenticationRes_Body) ProtoMessage() {}

func (x *Message_AuthenticationRes_Body) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_AuthenticationRes_Body.ProtoReflect.Descriptor instead.
func (*Message_AuthenticationRes_Body) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *Message_AuthenticationRes_Body) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *Message_AuthenticationRes_Body) GetNode() *core.Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *Message_AuthenticationRes_Body) GetNodeAddress() *core.NodeAddress {
	if x != nil {
		return x.NodeAddress
	}
	return nil
}

type Message_NodePub_Body struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         []byte                 `protobuf:"bytes,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	NodeId        []byte                 `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Node          *core.Node             `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	NodeAddress   *core.NodeAddress      `protobuf:"bytes,4,opt,name=nodeAddress,proto3" json:"nodeAddress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_NodePub_Body) Reset() {
	*x = Message_NodePub_Body{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_NodePub_Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_NodePub_Body) ProtoMessage() {}

func (x *Message_NodePub_Body) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_NodePub_Body.ProtoReflect.Descriptor instead.
func (*Message_NodePub_Body) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 3, 0}
}

func (x *Message_NodePub_Body) GetMsgId() []byte {
	if x != nil {
		return x.MsgId
	}
	return nil
}

func (x *Message_NodePub_Body) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *Message_NodePub_Body) GetNode() *core.Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *Message_NodePub_Body) GetNodeAddress() *core.NodeAddress {
	if x != nil {
		return x.NodeAddress
	}
	return nil
}

type Message_BlockPub_Body struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         []byte                 `protobuf:"bytes,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	NodeId        []byte                 `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Block         *core.Block            `protobuf:"bytes,3,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_BlockPub_Body) Reset() {
	*x = Message_BlockPub_Body{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_BlockPub_Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_BlockPub_Body) ProtoMessage() {}

func (x *Message_BlockPub_Body) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_BlockPub_Body.ProtoReflect.Descriptor instead.
func (*Message_BlockPub_Body) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 4, 0}
}

func (x *Message_BlockPub_Body) GetMsgId() []byte {
	if x != nil {
		return x.MsgId
	}
	return nil
}

func (x *Message_BlockPub_Body) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *Message_BlockPub_Body) GetBlock() *core.Block {
	if x != nil {
		return x.Block
	}
	return nil
}

type Message_PaymentReq_Body struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MsgId          []byte                 `protobuf:"bytes,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	NodeId         []byte                 `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	PaymentRequest *core.PaymentRequest   `protobuf:"bytes,3,opt,name=paymentRequest,proto3" json:"paymentRequest,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Message_PaymentReq_Body) Reset() {
	*x = Message_PaymentReq_Body{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_PaymentReq_Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_PaymentReq_Body) ProtoMessage() {}

func (x *Message_PaymentReq_Body) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_PaymentReq_Body.ProtoReflect.Descriptor instead.
func (*Message_PaymentReq_Body) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 5, 0}
}

func (x *Message_PaymentReq_Body) GetMsgId() []byte {
	if x != nil {
		return x.MsgId
	}
	return nil
}

func (x *Message_PaymentReq_Body) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *Message_PaymentReq_Body) GetPaymentRequest() *core.PaymentRequest {
	if x != nil {
		return x.PaymentRequest
	}
	return nil
}

type Message_BlockConfirmPub_Body struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         []byte                 `protobuf:"bytes,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	NodeId        []byte                 `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	BlockHash     []byte                 `protobuf:"bytes,3,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_BlockConfirmPub_Body) Reset() {
	*x = Message_BlockConfirmPub_Body{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_BlockConfirmPub_Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_BlockConfirmPub_Body) ProtoMessage() {}

func (x *Message_BlockConfirmPub_Body) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_BlockConfirmPub_Body.ProtoReflect.Descriptor instead.
func (*Message_BlockConfirmPub_Body) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 6, 0}
}

func (x *Message_BlockConfirmPub_Body) GetMsgId() []byte {
	if x != nil {
		return x.MsgId
	}
	return nil
}

func (x *Message_BlockConfirmPub_Body) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *Message_BlockConfirmPub_Body) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

type Message_BlockVerifyPub_Body struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         []byte                 `protobuf:"bytes,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	NodeId        []byte                 `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	BlockHash     []byte                 `protobuf:"bytes,3,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_BlockVerifyPub_Body) Reset() {
	*x = Message_BlockVerifyPub_Body{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_BlockVerifyPub_Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_BlockVerifyPub_Body) ProtoMessage() {}

func (x *Message_BlockVerifyPub_Body) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_BlockVerifyPub_Body.ProtoReflect.Descriptor instead.
func (*Message_BlockVerifyPub_Body) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 7, 0}
}

func (x *Message_BlockVerifyPub_Body) GetMsgId() []byte {
	if x != nil {
		return x.MsgId
	}
	return nil
}

func (x *Message_BlockVerifyPub_Body) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *Message_BlockVerifyPub_Body) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

type Message_BlockVerifyConfirmPub_Body struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         []byte                 `protobuf:"bytes,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	NodeId        []byte                 `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	BlockHash     []byte                 `protobuf:"bytes,3,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_BlockVerifyConfirmPub_Body) Reset() {
	*x = Message_BlockVerifyConfirmPub_Body{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_BlockVerifyConfirmPub_Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_BlockVerifyConfirmPub_Body) ProtoMessage() {}

func (x *Message_BlockVerifyConfirmPub_Body) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_BlockVerifyConfirmPub_Body.ProtoReflect.Descriptor instead.
func (*Message_BlockVerifyConfirmPub_Body) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 8, 0}
}

func (x *Message_BlockVerifyConfirmPub_Body) GetMsgId() []byte {
	if x != nil {
		return x.MsgId
	}
	return nil
}

func (x *Message_BlockVerifyConfirmPub_Body) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *Message_BlockVerifyConfirmPub_Body) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

type Message_FrontierRes_Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       []byte                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_FrontierRes_Entry) Reset() {
	*x = Message_FrontierRes_Entry{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_FrontierRes_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_FrontierRes_Entry) ProtoMessage() {}

func (x *Message_FrontierRes_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_FrontierRes_Entry.ProtoReflect.Descriptor instead.
func (*Message_FrontierRes_Entry) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 12, 0}
}

func (x *Message_FrontierRes_Entry) GetAccount() []byte {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *Message_FrontierRes_Entry) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type Message_ConfirmReqByHash_HashPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	First         []byte                 `protobuf:"bytes,1,opt,name=first,proto3" json:"first,omitempty"`
	Second        []byte                 `protobuf:"bytes,2,opt,name=second,proto3" json:"second,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_ConfirmReqByHash_HashPair) Reset() {
	*x = Message_ConfirmReqByHash_HashPair{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_ConfirmReqByHash_HashPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_ConfirmReqByHash_HashPair) ProtoMessage() {}

func (x *Message_ConfirmReqByHash_HashPair) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_ConfirmReqByHash_HashPair.ProtoReflect.Descriptor instead.
func (*Message_ConfirmReqByHash_HashPair) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 20, 0}
}

func (x *Message_ConfirmReqByHash_HashPair) GetFirst() []byte {
	if x != nil {
		return x.First
	}
	return nil
}

func (x *Message_ConfirmReqByHash_HashPair) GetSecond() []byte {
	if x != nil {
		return x.Second
	}
	return nil
}

type Message_ConfirmRes_VoteCommon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       []byte                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Sequence      int64                  `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_ConfirmRes_VoteCommon) Reset() {
	*x = Message_ConfirmRes_VoteCommon{}
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_ConfirmRes_VoteCommon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_ConfirmRes_VoteCommon) ProtoMessage() {}

func (x *Message_ConfirmRes_VoteCommon) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_broker_comm_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_ConfirmRes_VoteCommon.ProtoReflect.Descriptor instead.
func (*Message_ConfirmRes_VoteCommon) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_broker_comm_proto_rawDescGZIP(), []int{0, 23, 0}
}

func (x *Message_ConfirmRes_VoteCommon) GetAccount() []byte {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *Message_ConfirmRes_VoteCommon) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Message_ConfirmRes_VoteCommon) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

var File_libs_schema_pkg_broker_comm_proto protoreflect.FileDescriptor

var file_libs_schema_pkg_broker_comm_proto_rawDesc = string([]byte{
	0x0a, 0x21, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x10, 0x66, 0x6c, 0x69, 0x6e, 0x6b, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x62,
	0x72, 0x6f, 0x6b, 0x65, 0x72, 0x1a, 0x1f, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x73, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x63, 0x6f, 0x72, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x94, 0x20, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x61,
	0x67, 0x69, 0x63, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x65, 0x74, 0x6f, 0x77, 0x72, 0x6b, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6e, 0x65, 0x74, 0x6f, 0x77, 0x72, 0x6b, 0x49,
	0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x78, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x4d, 0x61,
	0x78, 0x12, 0x22, 0x0a, 0x0c, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x55, 0x73, 0x69, 0x6e,
	0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x55, 0x73, 0x69, 0x6e, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x4d, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x4d, 0x69, 0x6e, 0x12, 0x26, 0x0a, 0x03, 0x61, 0x6e, 0x79, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x03, 0x61, 0x6e, 0x79, 0x1a, 0x7f, 0x0a,
	0x08, 0x49, 0x41, 0x6d, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x12, 0x3d, 0x0a, 0x05, 0x70, 0x65, 0x65,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x66, 0x6c, 0x69, 0x6e, 0x6b,
	0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x49, 0x41, 0x6d, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x2e, 0x50, 0x65, 0x65,
	0x72, 0x52, 0x05, 0x70, 0x65, 0x65, 0x72, 0x73, 0x1a, 0x34, 0x0a, 0x04, 0x50, 0x65, 0x65, 0x72,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f,
	0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x1a, 0x29,
	0x0a, 0x11, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0xff, 0x01, 0x0a, 0x11, 0x41, 0x75,
	0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x12,
	0x44, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e,
	0x66, 0x6c, 0x69, 0x6e, 0x6b, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x2e, 0x42, 0x6f, 0x64, 0x79, 0x52,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x1a, 0x85, 0x01, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x28, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x66, 0x6c, 0x69, 0x6e, 0x6b, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x63, 0x6f, 0x72,
	0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x3d, 0x0a, 0x0b,
	0x6e, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x66, 0x6c, 0x69, 0x6e, 0x6b, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x63, 0x6f,
	0x72, 0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x0b,
	0x6e, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x1a, 0x83, 0x02, 0x0a, 0x07,
	0x4e, 0x6f, 0x64, 0x65, 0x50, 0x75, 0x62, 0x12, 0x3a, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x66, 0x6c, 0x69, 0x6e, 0x6b, 0x63, 0x6f, 0x69,
	0x6e, 0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x75, 0x62, 0x2e, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x1a, 0x9d, 0x01, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73,
	0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x66, 0x6c, 0x69, 0x6e, 0x6b, 0x63, 0x6f,
	0x69, 0x6e, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6e, 0x6f,
	0x64, 0x65, 0x12, 0x3d, 0x0a, 0x0b, 0x6e, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x66, 0x6c, 0x69, 0x6e, 0x6b, 0x63,
	0x6f, 0x69, 0x6e, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x52, 0x0b, 0x6e, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x1a, 0xc8, 0x01, 0x0a, 0x08, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x75, 0x62, 0x12, 0x3b,
	0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x66,
	0x6c, 0x69, 0x6e, 0x6b, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x75, 0x62,
	0x2e, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x1a, 0x61, 0x0a, 0x04, 0x42, 0x6f, 0x64,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12,
	0x2b, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x66, 0x6c, 0x69, 0x6e, 0x6b, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x1a, 0xe7, 0x01, 0x0a,
	0x0a, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x3d, 0x0a, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x66, 0x6c, 0x69, 0x6e,
	0x6b, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x2e,
	0x42, 0x6f, 0x64, 0x79, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x1a, 0x7c, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x46,
	0x0a, 0x0e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x66, 0x6c, 0x69, 0x6e, 0x6b, 0x63, 0x6f,
	0x69, 0x6e, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0xc7, 0x01, 0x0a, 0x0f, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x50, 0x75, 0x62, 0x12, 0x42, 0x0a, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x66, 0x6c, 0x69, 0x6e, 0x6b,
	0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d,
	0x50, 0x75, 0x62, 0x2e, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x1a, 0x52, 0x0a, 0x04,
	0x42, 0x6f, 0x64, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f,
	0x64, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68,
	0x1a, 0xc5, 0x01, 0x0a, 0x0e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x50, 0x75, 0x62, 0x12, 0x41, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x2d, 0x2e, 0x66, 0x6c, 0x69, 0x6e, 0x6b, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x62, 0x72,
	0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x50, 0x75, 0x62, 0x2e, 0x42, 0x6f, 0x64, 0x79,
	0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x1a, 0x52, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6d, 0x73, 0x67,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x1a, 0xd3, 0x01, 0x0a, 0x15, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x50,
	0x75, 0x62, 0x12, 0x48, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x34, 0x2e, 0x66, 0x6c, 0x69, 0x6e, 0x6b, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x62, 0x72, 0x6f,
	0x6b, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x50, 0x75,
	0x62, 0x2e, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x1a, 0x52, 0x0a, 0x04, 0x42, 0x6f,
	0x64, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x1a, 0x66,
	0x0a, 0x08, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x66, 0x72, 0x6f, 0x6d,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0d, 0x66, 0x72, 0x6f, 0x6d, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x81, 0x01, 0x0a, 0x08, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x52, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x24, 0x0a, 0x0d, 0x66, 0x72, 0x6f, 0x6d, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61,
	0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x66, 0x72, 0x6f, 0x6d, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x12, 0x31, 0x0a, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x66, 0x6c, 0x69, 0x6e, 0x6b, 0x63,
	0x6f, 0x69, 0x6e, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x46, 0x75, 0x6c, 0x6c, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x52, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x1a, 0x4b, 0x0a, 0x0b, 0x46, 0x72,
	0x6f, 0x6e, 0x74, 0x69, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x8b, 0x01, 0x0a, 0x0b, 0x46, 0x72, 0x6f, 0x6e,
	0x74, 0x69, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x45, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x66, 0x6c, 0x69, 0x6e, 0x6b,
	0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x69, 0x65, 0x72, 0x52, 0x65, 0x73, 0x2e,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x1a, 0x35,
	0x0a, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x68, 0x61, 0x73, 0x68, 0x1a, 0x3b, 0x0a, 0x0c, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74,
	0x72, 0x79, 0x52, 0x65, 0x71, 0x12, 0x2b, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x66, 0x6c, 0x69, 0x6e, 0x6b, 0x63, 0x6f, 0x69, 0x6e,
	0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x05, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x1a, 0xba, 0x04, 0x0a, 0x0c, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x12, 0x63, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x65, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x64, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x30, 0x0a, 0x13, 0x75, 0x6e, 0x63,
	0x68, 0x65, 0x63, 0x6b, 0x65, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x13, 0x75, 0x6e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65,
	0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x22, 0x0a, 0x0c, 0x62, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x43, 0x61, 0x70, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x62, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68,
	0x43, 0x61, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70,
	0x65, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x70, 0x65, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x67, 0x65, 0x6e, 0x65, 0x73, 0x69, 0x73, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x67, 0x65, 0x6e, 0x65, 0x73,
	0x69, 0x73, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x61, 0x6a, 0x6f, 0x72,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x6d,
	0x61, 0x6a, 0x6f, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x6d,
	0x69, 0x6e, 0x6f, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0d, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0c, 0x6d, 0x69, 0x6e, 0x6f, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x6d, 0x61, 0x6b, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x2a, 0x0a, 0x10, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x44, 0x69, 0x66,
	0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x18, 0x10, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x44, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x1a,
	0x36, 0x0a, 0x07, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x12, 0x2b, 0x0a, 0x05, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x66, 0x6c, 0x69, 0x6e,
	0x6b, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x1a, 0x6a, 0x0a, 0x0f, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x42, 0x75, 0x6c, 0x6b, 0x50, 0x75, 0x73, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x73, 0x74, 0x6f, 0x70, 0x12, 0x2d, 0x0a, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x66, 0x6c, 0x69, 0x6e, 0x6b, 0x63, 0x6f, 0x69, 0x6e,
	0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x06, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x73, 0x1a, 0x51, 0x0a, 0x0f, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x75,
	0x6c, 0x6b, 0x50, 0x75, 0x6c, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x74, 0x6f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x74, 0x6f, 0x70,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x63, 0x0a, 0x08, 0x42, 0x75, 0x6c, 0x6b, 0x50, 0x75,
	0x73, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x6f, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x12, 0x2d, 0x0a, 0x06,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x66,
	0x6c, 0x69, 0x6e, 0x6b, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x52, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x1a, 0x4a, 0x0a, 0x08, 0x42,
	0x75, 0x6c, 0x6b, 0x50, 0x75, 0x6c, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x74, 0x6f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x74, 0x6f,
	0x70, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x9f, 0x01, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x42, 0x79, 0x48, 0x61, 0x73, 0x68, 0x12, 0x51, 0x0a, 0x09,
	0x68, 0x61, 0x73, 0x68, 0x50, 0x61, 0x69, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x33, 0x2e, 0x66, 0x6c, 0x69, 0x6e, 0x6b, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x62, 0x72, 0x6f, 0x6b,
	0x65, 0x72, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x72, 0x6d, 0x52, 0x65, 0x71, 0x42, 0x79, 0x48, 0x61, 0x73, 0x68, 0x2e, 0x48, 0x61, 0x73, 0x68,
	0x50, 0x61, 0x69, 0x72, 0x52, 0x09, 0x68, 0x61, 0x73, 0x68, 0x50, 0x61, 0x69, 0x72, 0x73, 0x1a,
	0x38, 0x0a, 0x08, 0x48, 0x61, 0x73, 0x68, 0x50, 0x61, 0x69, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x66,
	0x69, 0x72, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x66, 0x69, 0x72, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x1a, 0x91, 0x01, 0x0a, 0x0a, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x56, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x42, 0x79, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x66, 0x6c, 0x69, 0x6e, 0x6b, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x62,
	0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x42, 0x79, 0x48, 0x61, 0x73, 0x68, 0x52, 0x10,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x42, 0x79, 0x48, 0x61, 0x73, 0x68,
	0x12, 0x2b, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x66, 0x6c, 0x69, 0x6e, 0x6b, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x63, 0x6f, 0x72, 0x65,
	0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x1a, 0x24, 0x0a,
	0x0a, 0x56, 0x6f, 0x74, 0x65, 0x42, 0x79, 0x48, 0x61, 0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68,
	0x61, 0x73, 0x68, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x68, 0x61, 0x73,
	0x68, 0x65, 0x73, 0x1a, 0xb2, 0x02, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52,
	0x65, 0x73, 0x12, 0x4f, 0x0a, 0x0a, 0x76, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x66, 0x6c, 0x69, 0x6e, 0x6b, 0x63, 0x6f,
	0x69, 0x6e, 0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52, 0x65, 0x73, 0x2e, 0x56, 0x6f, 0x74,
	0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x0a, 0x76, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x12, 0x44, 0x0a, 0x0a, 0x76, 0x6f, 0x74, 0x65, 0x42, 0x79, 0x48, 0x61, 0x73,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x66, 0x6c, 0x69, 0x6e, 0x6b, 0x63,
	0x6f, 0x69, 0x6e, 0x2e, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x42, 0x79, 0x48, 0x61, 0x73, 0x68, 0x52, 0x0a, 0x76,
	0x6f, 0x74, 0x65, 0x42, 0x79, 0x48, 0x61, 0x73, 0x68, 0x12, 0x2b, 0x0a, 0x05, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x66, 0x6c, 0x69, 0x6e, 0x6b,
	0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52,
	0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x1a, 0x60, 0x0a, 0x0a, 0x56, 0x6f, 0x74, 0x65, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x6c, 0x69, 0x6e, 0x6b, 0x63, 0x6f, 0x69, 0x6e,
	0x2f, 0x6d, 0x6f, 0x6e, 0x6f, 0x2f, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_libs_schema_pkg_broker_comm_proto_rawDescOnce sync.Once
	file_libs_schema_pkg_broker_comm_proto_rawDescData []byte
)

func file_libs_schema_pkg_broker_comm_proto_rawDescGZIP() []byte {
	file_libs_schema_pkg_broker_comm_proto_rawDescOnce.Do(func() {
		file_libs_schema_pkg_broker_comm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_libs_schema_pkg_broker_comm_proto_rawDesc), len(file_libs_schema_pkg_broker_comm_proto_rawDesc)))
	})
	return file_libs_schema_pkg_broker_comm_proto_rawDescData
}

var file_libs_schema_pkg_broker_comm_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_libs_schema_pkg_broker_comm_proto_goTypes = []any{
	(*Message)(nil),                            // 0: flinkcoin.broker.Message
	(*Message_IAmAlive)(nil),                   // 1: flinkcoin.broker.Message.IAmAlive
	(*Message_AuthenticationReq)(nil),          // 2: flinkcoin.broker.Message.AuthenticationReq
	(*Message_AuthenticationRes)(nil),          // 3: flinkcoin.broker.Message.AuthenticationRes
	(*Message_NodePub)(nil),                    // 4: flinkcoin.broker.Message.NodePub
	(*Message_BlockPub)(nil),                   // 5: flinkcoin.broker.Message.BlockPub
	(*Message_PaymentReq)(nil),                 // 6: flinkcoin.broker.Message.PaymentReq
	(*Message_BlockConfirmPub)(nil),            // 7: flinkcoin.broker.Message.BlockConfirmPub
	(*Message_BlockVerifyPub)(nil),             // 8: flinkcoin.broker.Message.BlockVerifyPub
	(*Message_BlockVerifyConfirmPub)(nil),      // 9: flinkcoin.broker.Message.BlockVerifyConfirmPub
	(*Message_BlockReq)(nil),                   // 10: flinkcoin.broker.Message.BlockReq
	(*Message_BlockRes)(nil),                   // 11: flinkcoin.broker.Message.BlockRes
	(*Message_FrontierReq)(nil),                // 12: flinkcoin.broker.Message.FrontierReq
	(*Message_FrontierRes)(nil),                // 13: flinkcoin.broker.Message.FrontierRes
	(*Message_TelemetryReq)(nil),               // 14: flinkcoin.broker.Message.TelemetryReq
	(*Message_TelemetryRes)(nil),               // 15: flinkcoin.broker.Message.TelemetryRes
	(*Message_Publish)(nil),                    // 16: flinkcoin.broker.Message.Publish
	(*Message_AccountBulkPush)(nil),            // 17: flinkcoin.broker.Message.AccountBulkPush
	(*Message_AccountBulkPull)(nil),            // 18: flinkcoin.broker.Message.AccountBulkPull
	(*Message_BulkPush)(nil),                   // 19: flinkcoin.broker.Message.BulkPush
	(*Message_BulkPull)(nil),                   // 20: flinkcoin.broker.Message.BulkPull
	(*Message_ConfirmReqByHash)(nil),           // 21: flinkcoin.broker.Message.ConfirmReqByHash
	(*Message_ConfirmReq)(nil),                 // 22: flinkcoin.broker.Message.ConfirmReq
	(*Message_VoteByHash)(nil),                 // 23: flinkcoin.broker.Message.VoteByHash
	(*Message_ConfirmRes)(nil),                 // 24: flinkcoin.broker.Message.ConfirmRes
	(*Message_IAmAlive_Peer)(nil),              // 25: flinkcoin.broker.Message.IAmAlive.Peer
	(*Message_AuthenticationRes_Body)(nil),     // 26: flinkcoin.broker.Message.AuthenticationRes.Body
	(*Message_NodePub_Body)(nil),               // 27: flinkcoin.broker.Message.NodePub.Body
	(*Message_BlockPub_Body)(nil),              // 28: flinkcoin.broker.Message.BlockPub.Body
	(*Message_PaymentReq_Body)(nil),            // 29: flinkcoin.broker.Message.PaymentReq.Body
	(*Message_BlockConfirmPub_Body)(nil),       // 30: flinkcoin.broker.Message.BlockConfirmPub.Body
	(*Message_BlockVerifyPub_Body)(nil),        // 31: flinkcoin.broker.Message.BlockVerifyPub.Body
	(*Message_BlockVerifyConfirmPub_Body)(nil), // 32: flinkcoin.broker.Message.BlockVerifyConfirmPub.Body
	(*Message_FrontierRes_Entry)(nil),          // 33: flinkcoin.broker.Message.FrontierRes.Entry
	(*Message_ConfirmReqByHash_HashPair)(nil),  // 34: flinkcoin.broker.Message.ConfirmReqByHash.HashPair
	(*Message_ConfirmRes_VoteCommon)(nil),      // 35: flinkcoin.broker.Message.ConfirmRes.VoteCommon
	(*anypb.Any)(nil),                          // 36: google.protobuf.Any
	(*core.FullBlock)(nil),                     // 37: flinkcoin.core.FullBlock
	(*core.Block)(nil),                         // 38: flinkcoin.core.Block
	(*core.Node)(nil),                          // 39: flinkcoin.core.Node
	(*core.NodeAddress)(nil),                   // 40: flinkcoin.core.NodeAddress
	(*core.PaymentRequest)(nil),                // 41: flinkcoin.core.PaymentRequest
}
var file_libs_schema_pkg_broker_comm_proto_depIdxs = []int32{
	36, // 0: flinkcoin.broker.Message.any:type_name -> google.protobuf.Any
	25, // 1: flinkcoin.broker.Message.IAmAlive.peers:type_name -> flinkcoin.broker.Message.IAmAlive.Peer
	26, // 2: flinkcoin.broker.Message.AuthenticationRes.body:type_name -> flinkcoin.broker.Message.AuthenticationRes.Body
	27, // 3: flinkcoin.broker.Message.NodePub.body:type_name -> flinkcoin.broker.Message.NodePub.Body
	28, // 4: flinkcoin.broker.Message.BlockPub.body:type_name -> flinkcoin.broker.Message.BlockPub.Body
	29, // 5: flinkcoin.broker.Message.PaymentReq.body:type_name -> flinkcoin.broker.Message.PaymentReq.Body
	30, // 6: flinkcoin.broker.Message.BlockConfirmPub.body:type_name -> flinkcoin.broker.Message.BlockConfirmPub.Body
	31, // 7: flinkcoin.broker.Message.BlockVerifyPub.body:type_name -> flinkcoin.broker.Message.BlockVerifyPub.Body
	32, // 8: flinkcoin.broker.Message.BlockVerifyConfirmPub.body:type_name -> flinkcoin.broker.Message.BlockVerifyConfirmPub.Body
	37, // 9: flinkcoin.broker.Message.BlockRes.blocks:type_name -> flinkcoin.core.FullBlock
	33, // 10: flinkcoin.broker.Message.FrontierRes.entries:type_name -> flinkcoin.broker.Message.FrontierRes.Entry
	38, // 11: flinkcoin.broker.Message.TelemetryReq.block:type_name -> flinkcoin.core.Block
	38, // 12: flinkcoin.broker.Message.Publish.block:type_name -> flinkcoin.core.Block
	38, // 13: flinkcoin.broker.Message.AccountBulkPush.blocks:type_name -> flinkcoin.core.Block
	38, // 14: flinkcoin.broker.Message.BulkPush.blocks:type_name -> flinkcoin.core.Block
	34, // 15: flinkcoin.broker.Message.ConfirmReqByHash.hashPairs:type_name -> flinkcoin.broker.Message.ConfirmReqByHash.HashPair
	21, // 16: flinkcoin.broker.Message.ConfirmReq.confirmReqByHash:type_name -> flinkcoin.broker.Message.ConfirmReqByHash
	38, // 17: flinkcoin.broker.Message.ConfirmReq.block:type_name -> flinkcoin.core.Block
	35, // 18: flinkcoin.broker.Message.ConfirmRes.voteCommon:type_name -> flinkcoin.broker.Message.ConfirmRes.VoteCommon
	23, // 19: flinkcoin.broker.Message.ConfirmRes.voteByHash:type_name -> flinkcoin.broker.Message.VoteByHash
	38, // 20: flinkcoin.broker.Message.ConfirmRes.block:type_name -> flinkcoin.core.Block
	39, // 21: flinkcoin.broker.Message.AuthenticationRes.Body.node:type_name -> flinkcoin.core.Node
	40, // 22: flinkcoin.broker.Message.AuthenticationRes.Body.nodeAddress:type_name -> flinkcoin.core.NodeAddress
	39, // 23: flinkcoin.broker.Message.NodePub.Body.node:type_name -> flinkcoin.core.Node
	40, // 24: flinkcoin.broker.Message.NodePub.Body.nodeAddress:type_name -> flinkcoin.core.NodeAddress
	38, // 25: flinkcoin.broker.Message.BlockPub.Body.block:type_name -> flinkcoin.core.Block
	41, // 26: flinkcoin.broker.Message.PaymentReq.Body.paymentRequest:type_name -> flinkcoin.core.PaymentRequest
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_libs_schema_pkg_broker_comm_proto_init() }
func file_libs_schema_pkg_broker_comm_proto_init() {
	if File_libs_schema_pkg_broker_comm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_libs_schema_pkg_broker_comm_proto_rawDesc), len(file_libs_schema_pkg_broker_comm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_libs_schema_pkg_broker_comm_proto_goTypes,
		DependencyIndexes: file_libs_schema_pkg_broker_comm_proto_depIdxs,
		MessageInfos:      file_libs_schema_pkg_broker_comm_proto_msgTypes,
	}.Build()
	File_libs_schema_pkg_broker_comm_proto = out.File
	file_libs_schema_pkg_broker_comm_proto_goTypes = nil
	file_libs_schema_pkg_broker_comm_proto_depIdxs = nil
}
