// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: libs/schema/pkg/cashier/storage.proto

package cashier

import (
	core "github.com/flinkcoin/mono/libs/schema/pkg/core"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnclaimedInfoBlock_Action int32

const (
	UnclaimedInfoBlock_CREATE UnclaimedInfoBlock_Action = 0
	UnclaimedInfoBlock_DELETE UnclaimedInfoBlock_Action = 1
)

// Enum value maps for UnclaimedInfoBlock_Action.
var (
	UnclaimedInfoBlock_Action_name = map[int32]string{
		0: "CREATE",
		1: "DELETE",
	}
	UnclaimedInfoBlock_Action_value = map[string]int32{
		"CREATE": 0,
		"DELETE": 1,
	}
)

func (x UnclaimedInfoBlock_Action) Enum() *UnclaimedInfoBlock_Action {
	p := new(UnclaimedInfoBlock_Action)
	*p = x
	return p
}

func (x UnclaimedInfoBlock_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UnclaimedInfoBlock_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_libs_schema_pkg_cashier_storage_proto_enumTypes[0].Descriptor()
}

func (UnclaimedInfoBlock_Action) Type() protoreflect.EnumType {
	return &file_libs_schema_pkg_cashier_storage_proto_enumTypes[0]
}

func (x UnclaimedInfoBlock_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UnclaimedInfoBlock_Action.Descriptor instead.
func (UnclaimedInfoBlock_Action) EnumDescriptor() ([]byte, []int) {
	return file_libs_schema_pkg_cashier_storage_proto_rawDescGZIP(), []int{2, 0}
}

type NodePair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *core.Node             `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodePair) Reset() {
	*x = NodePair{}
	mi := &file_libs_schema_pkg_cashier_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodePair) ProtoMessage() {}

func (x *NodePair) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_cashier_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodePair.ProtoReflect.Descriptor instead.
func (*NodePair) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_cashier_storage_proto_rawDescGZIP(), []int{0}
}

func (x *NodePair) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *NodePair) GetValue() *core.Node {
	if x != nil {
		return x.Value
	}
	return nil
}

type NodeAddressPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *core.NodeAddress      `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeAddressPair) Reset() {
	*x = NodeAddressPair{}
	mi := &file_libs_schema_pkg_cashier_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeAddressPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeAddressPair) ProtoMessage() {}

func (x *NodeAddressPair) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_cashier_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeAddressPair.ProtoReflect.Descriptor instead.
func (*NodeAddressPair) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_cashier_storage_proto_rawDescGZIP(), []int{1}
}

func (x *NodeAddressPair) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *NodeAddressPair) GetValue() *core.NodeAddress {
	if x != nil {
		return x.Value
	}
	return nil
}

type UnclaimedInfoBlock struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	AccountId     []byte                    `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Action        UnclaimedInfoBlock_Action `protobuf:"varint,2,opt,name=action,proto3,enum=flinkcoin.cashier.UnclaimedInfoBlock_Action" json:"action,omitempty"`
	BlockHash     []byte                    `protobuf:"bytes,3,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnclaimedInfoBlock) Reset() {
	*x = UnclaimedInfoBlock{}
	mi := &file_libs_schema_pkg_cashier_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnclaimedInfoBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnclaimedInfoBlock) ProtoMessage() {}

func (x *UnclaimedInfoBlock) ProtoReflect() protoreflect.Message {
	mi := &file_libs_schema_pkg_cashier_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnclaimedInfoBlock.ProtoReflect.Descriptor instead.
func (*UnclaimedInfoBlock) Descriptor() ([]byte, []int) {
	return file_libs_schema_pkg_cashier_storage_proto_rawDescGZIP(), []int{2}
}

func (x *UnclaimedInfoBlock) GetAccountId() []byte {
	if x != nil {
		return x.AccountId
	}
	return nil
}

func (x *UnclaimedInfoBlock) GetAction() UnclaimedInfoBlock_Action {
	if x != nil {
		return x.Action
	}
	return UnclaimedInfoBlock_CREATE
}

func (x *UnclaimedInfoBlock) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

var File_libs_schema_pkg_cashier_storage_proto protoreflect.FileDescriptor

var file_libs_schema_pkg_cashier_storage_proto_rawDesc = string([]byte{
	0x0a, 0x25, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x63, 0x61, 0x73, 0x68, 0x69, 0x65, 0x72, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x66, 0x6c, 0x69, 0x6e, 0x6b, 0x63, 0x6f,
	0x69, 0x6e, 0x2e, 0x63, 0x61, 0x73, 0x68, 0x69, 0x65, 0x72, 0x1a, 0x1f, 0x6c, 0x69, 0x62, 0x73,
	0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x72, 0x65,
	0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x48, 0x0a, 0x08, 0x4e,
	0x6f, 0x64, 0x65, 0x50, 0x61, 0x69, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x66, 0x6c, 0x69, 0x6e, 0x6b,
	0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x56, 0x0a, 0x0f, 0x4e, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x50, 0x61, 0x69, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x31, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x66, 0x6c, 0x69, 0x6e,
	0x6b, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xb8, 0x01,
	0x0a, 0x12, 0x55, 0x6e, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x65, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x44, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x2c, 0x2e, 0x66, 0x6c, 0x69, 0x6e, 0x6b, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x63,
	0x61, 0x73, 0x68, 0x69, 0x65, 0x72, 0x2e, 0x55, 0x6e, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x65, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x22, 0x20, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x0a, 0x0a, 0x06, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x01, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x6c, 0x69, 0x6e, 0x6b, 0x63, 0x6f, 0x69, 0x6e,
	0x2f, 0x6d, 0x6f, 0x6e, 0x6f, 0x2f, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x61, 0x73, 0x68, 0x69, 0x65, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_libs_schema_pkg_cashier_storage_proto_rawDescOnce sync.Once
	file_libs_schema_pkg_cashier_storage_proto_rawDescData []byte
)

func file_libs_schema_pkg_cashier_storage_proto_rawDescGZIP() []byte {
	file_libs_schema_pkg_cashier_storage_proto_rawDescOnce.Do(func() {
		file_libs_schema_pkg_cashier_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_libs_schema_pkg_cashier_storage_proto_rawDesc), len(file_libs_schema_pkg_cashier_storage_proto_rawDesc)))
	})
	return file_libs_schema_pkg_cashier_storage_proto_rawDescData
}

var file_libs_schema_pkg_cashier_storage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_libs_schema_pkg_cashier_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_libs_schema_pkg_cashier_storage_proto_goTypes = []any{
	(UnclaimedInfoBlock_Action)(0), // 0: flinkcoin.cashier.UnclaimedInfoBlock.Action
	(*NodePair)(nil),               // 1: flinkcoin.cashier.NodePair
	(*NodeAddressPair)(nil),        // 2: flinkcoin.cashier.NodeAddressPair
	(*UnclaimedInfoBlock)(nil),     // 3: flinkcoin.cashier.UnclaimedInfoBlock
	(*core.Node)(nil),              // 4: flinkcoin.core.Node
	(*core.NodeAddress)(nil),       // 5: flinkcoin.core.NodeAddress
}
var file_libs_schema_pkg_cashier_storage_proto_depIdxs = []int32{
	4, // 0: flinkcoin.cashier.NodePair.value:type_name -> flinkcoin.core.Node
	5, // 1: flinkcoin.cashier.NodeAddressPair.value:type_name -> flinkcoin.core.NodeAddress
	0, // 2: flinkcoin.cashier.UnclaimedInfoBlock.action:type_name -> flinkcoin.cashier.UnclaimedInfoBlock.Action
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_libs_schema_pkg_cashier_storage_proto_init() }
func file_libs_schema_pkg_cashier_storage_proto_init() {
	if File_libs_schema_pkg_cashier_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_libs_schema_pkg_cashier_storage_proto_rawDesc), len(file_libs_schema_pkg_cashier_storage_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_libs_schema_pkg_cashier_storage_proto_goTypes,
		DependencyIndexes: file_libs_schema_pkg_cashier_storage_proto_depIdxs,
		EnumInfos:         file_libs_schema_pkg_cashier_storage_proto_enumTypes,
		MessageInfos:      file_libs_schema_pkg_cashier_storage_proto_msgTypes,
	}.Build()
	File_libs_schema_pkg_cashier_storage_proto = out.File
	file_libs_schema_pkg_cashier_storage_proto_goTypes = nil
	file_libs_schema_pkg_cashier_storage_proto_depIdxs = nil
}
