// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/flinkcoin/mono/apps/broker/internal/config"
	"github.com/flinkcoin/mono/apps/broker/internal/net"
	"github.com/flinkcoin/mono/libs/core/pkg"
)

// Injectors from wire.go:

func Init() *Broker {
	slogLogger := pkg.NewLogger()
	configConfig := config.NewConfig(slogLogger)
	harborHarbor := net.NewNode(slogLogger)
	app := NewBroker(slogLogger, configConfig, harborHarbor)
	return app
}
